# Generates the CUDA kernel-registration translation unit for one single-source
# _gpu.h file (docs/metal-rhi-design.md M4; rhi_cuda.h). Run at build time by
# the fluora_cuda_kernels() function in CMakeLists.txt:
#
#   cmake -DINPUT=<header> -DOUTPUT=<file.cu> [-DINCLUDES=<h1;h2;...>]
#         [-DREGISTRY_HEADER=<rhi_cuda.h>] -P GenerateCudaKernels.cmake
#
# The header is scanned for
#   GPU_KERNEL(name)                       -> RHI_CUDA_REGISTER_KERNEL(name)
#   GPU_SPEC_INSTANCES(name, idx, v1, ...) -> RHI_CUDA_REGISTER_SPEC(name, idx, v)
#                                             per value (no plain registration)
# A kernel declared right after GPU_SPEC_CONST must list its instances, since
# the template cannot be registered unspecialized; that is a hard error here so
# it fails at configure/build time instead of at pipeline creation.
#
# INCLUDES are emitted before the header for concat-style headers that do not
# include their own dependencies (shared_probe.h). The Metal backend needs none
# of this: it compiles the same header from source at runtime.

if(NOT INPUT OR NOT OUTPUT)
    message(FATAL_ERROR "GenerateCudaKernels: INPUT and OUTPUT are required")
endif()
if(NOT REGISTRY_HEADER)
    get_filename_component(_here "${CMAKE_CURRENT_LIST_DIR}" ABSOLUTE)
    set(REGISTRY_HEADER "${_here}/../src/rhi/rhi_cuda.h")
endif()
get_filename_component(REGISTRY_HEADER "${REGISTRY_HEADER}" ABSOLUTE)
get_filename_component(INPUT "${INPUT}" ABSOLUTE)

file(READ "${INPUT}" _src)

# Kernels: GPU_KERNEL(name) -- GPU_KERNEL_PARAMS(...) does not match because
# the macro name is followed by "_PARAMS", not "(".
set(_kernels "")
string(REGEX MATCHALL "GPU_KERNEL\\(([A-Za-z_][A-Za-z_0-9]*)\\)" _kmatches "${_src}")
foreach(_m IN LISTS _kmatches)
    string(REGEX REPLACE "GPU_KERNEL\\(([A-Za-z_][A-Za-z_0-9]*)\\)" "\\1" _name "${_m}")
    list(APPEND _kernels "${_name}")
endforeach()
list(REMOVE_DUPLICATES _kernels)

# Templated kernels: GPU_SPEC_CONST(...) immediately followed by GPU_KERNEL(name).
set(_templated "")
string(REGEX MATCHALL "GPU_SPEC_CONST\\([^)]*\\)[ \t\r\n]*GPU_KERNEL\\(([A-Za-z_][A-Za-z_0-9]*)\\)" _tmatches "${_src}")
foreach(_m IN LISTS _tmatches)
    string(REGEX REPLACE ".*GPU_KERNEL\\(([A-Za-z_][A-Za-z_0-9]*)\\)" "\\1" _name "${_m}")
    list(APPEND _templated "${_name}")
endforeach()

# Specialization instances: GPU_SPEC_INSTANCES(name, index, v1, v2, ...).
set(_specLines "")
set(_specKernels "")
string(REGEX MATCHALL "GPU_SPEC_INSTANCES\\(([^)]*)\\)" _smatches "${_src}")
foreach(_m IN LISTS _smatches)
    string(REGEX REPLACE "GPU_SPEC_INSTANCES\\(([^)]*)\\)" "\\1" _args "${_m}")
    string(REPLACE "," ";" _args "${_args}")
    set(_clean "")
    foreach(_a IN LISTS _args)
        string(STRIP "${_a}" _a)
        list(APPEND _clean "${_a}")
    endforeach()
    list(LENGTH _clean _n)
    if(_n LESS 3)
        message(FATAL_ERROR "GenerateCudaKernels: ${INPUT}: GPU_SPEC_INSTANCES needs (kernel, index, value...) -- got '${_m}'")
    endif()
    list(GET _clean 0 _name)
    list(GET _clean 1 _index)
    list(APPEND _specKernels "${_name}")
    foreach(_i RANGE 2 ${_n})
        if(_i LESS _n)
            list(GET _clean ${_i} _v)
            string(APPEND _specLines "RHI_CUDA_REGISTER_SPEC(${_name}, ${_index}, ${_v});\n")
        endif()
    endforeach()
endforeach()

foreach(_t IN LISTS _templated)
    if(NOT "${_t}" IN_LIST _specKernels)
        message(FATAL_ERROR "GenerateCudaKernels: ${INPUT}: kernel '${_t}' is declared after GPU_SPEC_CONST but has no GPU_SPEC_INSTANCES(${_t}, index, values...) annotation")
    endif()
endforeach()

set(_out "// GENERATED by cmake/GenerateCudaKernels.cmake from\n//   ${INPUT}\n// Do not edit; add kernels to the header (and GPU_SPEC_INSTANCES for\n// specialized ones) and rebuild.\n")
foreach(_inc IN LISTS INCLUDES)
    get_filename_component(_inc "${_inc}" ABSOLUTE)
    string(APPEND _out "#include \"${_inc}\"\n")
endforeach()
string(APPEND _out "#include \"${INPUT}\"\n#include \"${REGISTRY_HEADER}\"\n\n")
foreach(_k IN LISTS _kernels)
    if(NOT "${_k}" IN_LIST _specKernels)
        string(APPEND _out "RHI_CUDA_REGISTER_KERNEL(${_k});\n")
    endif()
endforeach()
string(APPEND _out "${_specLines}")

# Only rewrite when the content changes so an untouched output does not
# retrigger nvcc.
set(_old "")
if(EXISTS "${OUTPUT}")
    file(READ "${OUTPUT}" _old)
endif()
if(NOT _old STREQUAL _out)
    file(WRITE "${OUTPUT}" "${_out}")
endif()
